from . filesystemview.filesystemview import  FileSystemView
from . panel_settings.panel_settings import PanelSettings
from . football.main import FootballWidget
from . home.main import HomeWidget
from . template.main import TemplatePage
from . tabs.tabs_east import TabsEast
from . tabs.tabs_west import TabsWest
from . tabs.tabs_north import TabsNorth
from . tabs.tabs_south import TabsSouth
